import jsPDF from 'jspdf';
import Logo from '../public/images/logo653_23.jpg';
import { formatDate } from './ReportDateHelper';
import formatDateToCustomFormat from './dateFormatter';
import 'jspdf-autotable';

const GeneratevehiclePDF = (dataa,role) => {
  const unit = 'mm';
  const size = 'a4';
  const orientation = 'portrait';
  const doc = new jsPDF(orientation, unit, size);
  const pageWidth = doc.internal.pageSize.getWidth();
  const imageSource = Logo.src;
  doc.setFont('CopperplateGothic', 'normal');
  // Logo in the top-left corner
  const newWidth = 100; // Set the new width you desire
  const aspectRatio = Logo.width / Logo.height;
  const newHeight = newWidth / aspectRatio;
  doc.addImage(imageSource, 'JPEG', -10, 0, newWidth, newHeight);

  // Current Date in the top-right corner
  const currentDate = formatDate(new Date());
  const dateText = `Date: ${currentDate}`;
  const dateTextWidth = doc.getTextWidth(dateText);
  const dateTextX = pageWidth - dateTextWidth - 15;
  doc.setFontSize(15);
  doc.text(dateText, dateTextX, 25);


  // Page Title
  const titleText = "VEHICLE ACCIDENT INVOLVEMENT REPORT ";
  doc.setFontSize(15);
  doc.text(titleText, 15, 55);

  // Separator Line
  doc.setLineWidth(0.5);
  doc.line(15, 60, pageWidth - 15, 60);


  // Report By
  doc.setFontSize(15);
  doc.text(`${role} REPORT`, 15, 92);

  // Line
  doc.setLineWidth(0.5);
  doc.setDrawColor('#2E5A88');
  doc.line(15, 95, pageWidth - 15, 95);

  // Report Details
  const startY = 105;
  const lineHeight = 15;
  let currentY = startY;
  let printableData=[]
  const formatData = dataa.map((data, index) => {
    return data.participants.map((participant, participantIndex) => {
      const lastname = participant.driver.lastname;
      const firstname = participant.driver.firstname;
      const driver=`${lastname} ${firstname}`
      const location = `${data.location.province} ${data.location.district}`;
      const drivingLicense = participant.driver.drivingLicense;
      const conclusion = participant.conclusion;
      const insuranceProvider=participant.vehicleInfo.insuranceProvider;
      const tookplaceon = formatDateToCustomFormat(data.createdAt);
      const status = data.caseStatus
      printableData.push({location, driver, drivingLicense, tookplaceon,insuranceProvider,conclusion, status})      
    });
  });
  const printData = printableData.map((data, index) => {
    const conclusion = data.conclusion
    const driver = data.driver;
    const location = data.location;
    const drivingLicense = data.drivingLicense;
    const insuranceProvider = data.insuranceProvider
    const status = data.status
    const tookplaceon = data.tookplaceon;

    return [index + 1, driver, location, drivingLicense, insuranceProvider, tookplaceon,conclusion, status];
  });

console.log(printData);

  // Auto-generate a table in the PDF using autoTable
  doc.autoTable({
    head: [['No.', 'DRIVER',"LOCATION", 'DRIVING LICENSE',"INSURANCE PROVIDER", 'TOOK PlACE ON',"REASON", 'CASE STATUS']],
    body: printData,
    startY: startY,
    margin: { top: 5, bottom: 5 }, // Reduced top and bottom margin
  });

  // Signature
  const signatureText = `Generated by ${role}`;
  doc.setFontSize(11);
  doc.text(signatureText, 15, doc.autoTable.previous.finalY + lineHeight);
  const signatureTextWidth = doc.getTextWidth(signatureText);
  const signatureDetailsX = 15 + signatureTextWidth + 10;
//   const signatureDetails = `${role}`;
//   doc.text(signatureDetails, signatureDetailsX, doc.autoTable.previous.finalY + lineHeight);

  // Final Line
  doc.setDrawColor('#739900');
  doc.line(15, doc.autoTable.previous.finalY + lineHeight * 2, pageWidth - 15, doc.autoTable.previous.finalY + lineHeight * 2);

  // Address Text
  const addressText = 'KN 25 Rd, KG 1 Ave, P.O. Box 0033, Nyarugenge, Kigali, Rwanda';
  const textFontSize = 8;
  const addressTextWidth = doc.getTextWidth(addressText);
  const addressTextX = (pageWidth - addressTextWidth) / 2;

  doc.setFontSize(textFontSize);
  doc.text(addressText, addressTextX, doc.autoTable.previous.finalY + lineHeight * 3);

  // Save PDF
  doc.save(`vehicle-report-${currentDate}.pdf`);
};

export default GeneratevehiclePDF;
